version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.5.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - image-network

        # images-server:
        #   image: images-server:latest
        #   container_name: images-server
        #   ports:
        #     - target: 8080
        #       published: 5174
        #   networks:
        #     -  image-network

  image-web:
    image: images-web:latest
    container_name: image-web
    ports:
      - target: 80
        published: 5173
    networks:
      -  image-network

  image-server-py:
    image: images-server-py:latest
    container_name: image-server-py
    ports:
      - target: 5000
        published: 5174
    environment:
      - FLASK_APP=server
      - FLASK_ENV=development

volumes:
  es_data:
    driver: local

networks:
  image-network:
    name: image-network
    driver: bridge
